// Copyright Amazon.com, Inc. or its affiliates. All Rights Reserved.
// SPDX-License-Identifier: MIT-0
export interface meeting {
  name: string;
  presenters: string;
  happened: string;
  ondemand: string;
  eventlink: string;
  // Optional stable jitsi room name. UUID per upcoming event so the URL is
  // not guessable by zoom-bombers. Past events can leave this empty.
  roomName?: string;
}

/*     sold: 5513,
    produced: 13837,
    estimated: 12331, */

export const meeting_type = ['Virtual', 'Hybrid', 'In-Person'];
export const services = [
  "AWS Amplify",
  "AWS App Mesh",
  "AWS App Runner",
  "AWS AppFabric",
  "AWS AppSync",
  "AWS Application Discovery Service",
  "AWS Application Migration Service (MGN)",
  "AWS Artifact",
  "AWS Audit Manager",
  "AWS Auto Scaling",
  "AWS Backup",
  "AWS Batch",
  "AWS Budgets",
  "AWS Certificate Manager",
  "AWS Chatbot",
  "AWS Clean Rooms",
  "AWS Cloud Control API",
  "AWS Cloud Map",
  "AWS Cloud9",
  "AWS CloudFormation",
  "AWS CloudHSM",
  "AWS CloudShell",
  "AWS CloudTrail",
  "AWS CodeArtifact",
  "AWS CodeBuild",
  "AWS CodeCommit",
  "AWS CodeDeploy",
  "AWS CodePipeline",
  "AWS CodeStar",
  "AWS Compute Optimizer",
  "AWS Config",
  "AWS Control Tower",
  "AWS Cost Explorer",
  "AWS Cost and Usage Report",
  "AWS Data Exchange",
  "AWS Data Pipeline",
  "AWS DataSync",
  "AWS Database Migration Service",
  "AWS Deadline Cloud",
  "AWS DeepComposer",
  "AWS DeepRacer",
  "AWS Direct Connect",
  "AWS Directory Service",
  "AWS Elastic Beanstalk",
  "AWS Elastic Disaster Recovery (DRS)",
  "AWS Elemental MediaConnect",
  "AWS Elemental MediaConvert",
  "AWS Elemental MediaLive",
  "AWS Elemental MediaPackage",
  "AWS Elemental MediaStore",
  "AWS Elemental MediaTailor",
  "AWS Entity Resolution",
  "AWS Fargate",
  "AWS Fault Injection Service",
  "AWS Firewall Manager",
  "AWS Global Accelerator",
  "AWS Glue",
  "AWS Ground Station",
  "AWS Health Dashboard",
  "AWS HealthImaging",
  "AWS HealthLake",
  "AWS HealthOmics",
  "AWS IAM Identity Center",
  "AWS IQ",
  "AWS Identity and Access Management (IAM)",
  "AWS IoT 1-Click",
  "AWS IoT Analytics",
  "AWS IoT Core",
  "AWS IoT Device Defender",
  "AWS IoT Device Management",
  "AWS IoT Events",
  "AWS IoT FleetWise",
  "AWS IoT Greengrass",
  "AWS IoT SiteWise",
  "AWS IoT TwinMaker",
  "AWS Key Management Service",
  "AWS Lake Formation",
  "AWS Lambda",
  "AWS Launch Wizard",
  "AWS License Manager",
  "AWS Mainframe Modernization",
  "AWS Managed Services",
  "AWS Marketplace",
  "AWS Migration Hub",
  "AWS Network Firewall",
  "AWS OpsWorks Stacks",
  "AWS OpsWorks for Chef Automate",
  "AWS OpsWorks for Puppet Enterprise",
  "AWS Organizations",
  "AWS Outposts",
  "AWS Payment Cryptography",
  "AWS Private 5G",
  "AWS Private Certificate Authority",
  "AWS PrivateLink",
  "AWS Proton",
  "AWS Resilience Hub",
  "AWS Resource Access Manager (RAM)",
  "AWS Resource Explorer",
  "AWS Resource Groups",
  "AWS RoboMaker",
  "AWS Secrets Manager",
  "AWS Security Hub",
  "AWS Serverless Application Repository",
  "AWS Service Catalog",
  "AWS Shield",
  "AWS Signer",
  "AWS SimSpace Weaver",
  "AWS Snowball",
  "AWS Snowcone",
  "AWS Step Functions",
  "AWS Storage Gateway",
  "AWS Support",
  "AWS Systems Manager",
  "AWS Telco Network Builder",
  "AWS Transfer Family",
  "AWS Transit Gateway",
  "AWS Trusted Advisor",
  "AWS User Notifications",
  "AWS VPN",
  "AWS Verified Access",
  "AWS WAF",
  "AWS Well-Architected Tool",
  "AWS Wickr",
  "AWS X-Ray",
  "Amazon API Gateway",
  "Amazon AppFlow",
  "Amazon AppStream 2.0",
  "Amazon Athena",
  "Amazon Augmented AI (A2I)",
  "Amazon Aurora",
  "Amazon Bedrock",
  "Amazon Braket",
  "Amazon Chime",
  "Amazon Chime SDK",
  "Amazon Cloud Directory",
  "Amazon CloudFront",
  "Amazon CloudSearch",
  "Amazon CloudWatch",
  "Amazon CloudWatch Logs",
  "Amazon CodeGuru",
  "Amazon CodeWhisperer",
  "Amazon Cognito",
  "Amazon Comprehend",
  "Amazon Comprehend Medical",
  "Amazon Connect",
  "Amazon Data Firehose",
  "Amazon DataZone",
  "Amazon Detective",
  "Amazon DevOps Guru",
  "Amazon DocumentDB (with MongoDB compatibility)",
  "Amazon DynamoDB",
  "Amazon DynamoDB Accelerator",
  "Amazon EC2 Auto Scaling",
  "Amazon ElastiCache",
  "Amazon Elastic Block Store (EBS)",
  "Amazon Elastic Compute Cloud (EC2)",
  "Amazon Elastic Container Registry (ECR)",
  "Amazon Elastic Container Service (ECS)",
  "Amazon Elastic File System (EFS)",
  "Amazon Elastic Inference",
  "Amazon Elastic Kubernetes Service (EKS)",
  "Amazon Elastic MapReduce (EMR)",
  "Amazon Elastic Transcoder",
  "Amazon EventBridge",
  "Amazon FSx",
  "Amazon FSx for Lustre",
  "Amazon FSx for NetApp ONTAP",
  "Amazon FSx for OpenZFS",
  "Amazon FSx for Windows File Server",
  "Amazon File Cache",
  "Amazon FinSpace",
  "Amazon Forecast",
  "Amazon Fraud Detector",
  "Amazon GameLift",
  "Amazon GuardDuty",
  "Amazon IVS",
  "Amazon Inspector",
  "Amazon Inspector Classic",
  "Amazon Kendra",
  "Amazon Keyspaces (for Apache Cassandra)",
  "Amazon Kinesis Data Streams",
  "Amazon Kinesis Video Streams",
  "Amazon Lex",
  "Amazon Lightsail",
  "Amazon Location Service",
  "Amazon Lookout for Metrics",
  "Amazon Lookout for Vision",
  "Amazon Lumberyard",
  "Amazon MQ",
  "Amazon Macie",
  "Amazon Managed Blockchain",
  "Amazon Managed Grafana",
  "Amazon Managed Service for Apache Flink",
  "Amazon Managed Service for Prometheus",
  "Amazon Managed Streaming for Apache Kafka",
  "Amazon Managed Workflows for Apache Airflow",
  "Amazon MemoryDB",
  "Amazon Monitron",
  "Amazon Neptune",
  "Amazon Nimble Studio",
  "Amazon OpenSearch Service",
  "Amazon Personalize",
  "Amazon Pinpoint and End User Messaging",
  "Amazon Polly",
  "Amazon Q Business",
  "Amazon Q Developer",
  "Amazon Quantum Ledger Database (QLDB)",
  "Amazon QuickSight",
  "Amazon RDS on VMware",
  "Amazon Redshift",
  "Amazon Rekognition",
  "Amazon Relational Database Service (RDS)",
  "Amazon Route 53",
  "Amazon SageMaker",
  "Amazon Security Lake",
  "Amazon Simple Email Service (SES)",
  "Amazon Simple Notification Service (SNS)",
  "Amazon Simple Queue Service (SQS)",
  "Amazon Simple Storage Service (S3)",
  "Amazon Simple Workflow Service (SWF)",
  "Amazon SimpleDB",
  "Amazon Textract",
  "Amazon Timestream",
  "Amazon Transcribe",
  "Amazon Translate",
  "Amazon VPC Lattice",
  "Amazon Verified Permissions",
  "Amazon Virtual Private Cloud (VPC)",
  "Amazon WorkDocs",
  "Amazon WorkMail",
  "Amazon WorkSpaces",
  "Amazon WorkSpaces Secure Browser",
  "Amazon WorkSpaces Thin Client",
  "CloudEndure Disaster Recovery",
  "CloudEndure Migration",
  "EC2 Image Builder",
  "Elastic Load Balancing",
  "FreeRTOS",
  "Red Hat OpenShift Service on AWS (ROSA)",
  "VMware Cloud on AWS",
];


export const variationsData: meeting[] = [
  {
    name: 'International Women\'s Day + Overcoming Imposter Syndrome',
    presenters: 'Dianne Eldridge | AWS, Colleen Tagle | Alamogordo Public Schools, Sabrina Diciano | AWS',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'meetup.com/awselftaught/events/284036919'
  },
  {
    name: 'The Free Tier. AWS Free for One Year.',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/284549815'
  },
  {
    name: 'Hands On Intro to Cloud',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/286046071'
  },
  {
    name: 'AWS Compute Meetup',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/286880326'
  },
  {
    name: 'Amazon Simple Storage Service (S3) Deep Dive',
    presenters: 'Brian Tarbox | AWS Hero @ Caylent',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/287513985'
  },
  {
    name: 'User Interface Design with Figma',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/287196780/'
  },
  {
    name: 'Going the Distance with 3D Web Rendering and BabylonJS',
    presenters: 'Josh Elster | Going the Distance author',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/287514027'
  },
  {
    name: 're:Cap and AWS Cloud Clubs intro',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/287514044'
  },
  {
    name: 'on Sustainability',
    presenters: 'Bryan Chasko | AWS Hero',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/290371991'
  },
  {
    name: 'Build a Weather Reminder App w/ AWS CDK',
    presenters: 'Jacob Wright | AWS Community Leader',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/290372311'
  },
  {
    name: 'Python Hands On',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/290372338'
  },
  {
    name: 'International Space Station Digital Twins',
    presenters: 'Boris Cortes | AWS',
    happened: 'true',
    ondemand: 'https://www.linkedin.com/posts/arrowhead-research-park_live-with-restream-powered-by-restream-https-activity-7052432537427574784-Lnrf',
    eventlink: 'https://www.meetup.com/awsaerospace/events/290372357'
  },
  {
    name: 'EC2 Cost Optimization',
    presenters: 'Siddharth Ambatipudi | AWS',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/290372383'
  },
  {
    name: 'AWS Aerospace and Satellite Discussion',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/293914491'
  },
  {
    name: 'Utilizing Generative AI Coding Assistants',
    presenters: 'Cameron Lofy | Turion Space',
    happened: 'true',
    ondemand: 'https://www.linkedin.com/posts/arrowhead-research-park_live-with-restream-powered-by-restream-https-activity-7095583153016225792-WGI9',
    eventlink: 'https://www.meetup.com/awsaerospace/events/290372402'
  },
  {
    name: 'Riot Games, AWS & Valorant Champions Tour',
    presenters: 'AMELIA HOUGH-ROSS | PNNL, Muhammad Qasim Shahzad | AWS Community Builder, Sammy Cheung | AWS Community Builder',
    happened: 'true',
    ondemand: 'https://www.linkedin.com/posts/arrowhead-research-park_vct-awsxvctchampions2023-esports-activity-7108246219499466752-DCT2',
    eventlink: 'https://www.meetup.com/awsaerospace/events/295825586'
  },
  {
    name: 'Satellite Ground Stations',
    presenters: 'David Lee | X2nSat, Oleg Grytsynevych | AWS',
    happened: 'true',
    ondemand: 'https://www.linkedin.com/posts/arrowhead-research-park_live-with-restream-powered-by-restream-https-activity-7118394944356044800--sDT',
    eventlink: 'https://www.meetup.com/awsaerospace/events/295832502'
  },
  {
    name: 'Using Generative AI in Satellite Imagery',
    presenters: 'Kathy O\' Donnel | AWS',
    happened: 'true',
    ondemand: 'https://www.linkedin.com/posts/arrowhead-research-park_live-with-restream-powered-by-restream-https-activity-7151380676045328384-uYve',
    eventlink: 'https://www.meetup.com/awsaerospace/events/298214167'
  },
  {
    name: 'How to re:Invent',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/296920128'
  },
  {
    name: 'Visualizing Wildfires with Earth Observation DAta',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/301822752'
  },
  {
    name: 'PartyRock Party',
    presenters: '',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/302124086'
  },
  {
    name: 'AWS Open Data Satellite Imagery & GitHub Foundations',
    presenters: 'Allen Helton | Believe in Serverless',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/302577569'
  },
  {
    name: 'Create an Alcohol Server Training Program with No Code',
    presenters: 'Bryan Chasko | AWS Hero',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.meetup.com/awsaerospace/events/302840839'
  },
  {
    name: 'Aerospace CEOs: Looking Forward',
    presenters: 'Brian Barnett | Solstar, Andrew Nelson | RS&H',
    happened: 'true',
    ondemand: 'no',
    eventlink: 'https://www.linkedin.com/posts/arrowhead-research-park_live-with-restream-powered-by-restream-https-activity-7072729359853260800-0TX3'
  },
  {
    name: 'Wednesday Website Work',
    presenters: 'Bryan Chasko, Jacob Wright',
    happened: 'false',
    ondemand: 'no',
    eventlink: '',
    // Pre-generated stable room name keeps the jitsi URL unguessable.
    roomName: 'wednesday-website-work-c8f21d9b'
  }

];
